[project]
name = "persona-explore"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.35.11",
    "python-fasthtml>=0.5.1",
]
